INFO  2019-05-18 17:40:28,870 (Saros.java:220) Starting Saros 14.10.31 running:
  Java Version: 11.0.2
  Java Vendor: Oracle Corporation
  Eclipse Runtime Version: 3.15.200.v20190301-1641
  Operating System: Windows 10 (10.0)
  Hardware Architecture: amd64
INFO  2019-05-18 17:40:28,903 (SarosContext.java:153) creating Saros runtime context...
DEBUG 2019-05-18 17:40:28,942 (XMPPAccountStore.java:117) loading accounts from file: C:\Users\Jannik\.saros\config.dat
DEBUG 2019-05-18 17:40:29,009 (XMPPAccountStore.java:176) loaded 1 account(s)
INFO  2019-05-18 17:40:29,150 (SarosContext.java:199) successfully created Saros runtime context
DEBUG 2019-05-18 17:40:29,170 (DataTransferManager.java:467) used transport order for the current XMPP connection: [XMPP-Socks5-Transport, XMPP-IBB-Transport]
INFO  2019-05-18 17:40:29,189 (PreferenceInitializer.java:50) initializing preference default values
DEBUG 2019-05-18 17:40:29,228 (SarosAnnotation.java:117) resetting annotation colors
DEBUG 2019-05-18 17:40:29,388 (Saros.java:430) skipping conversion of old XMPP accounts, because there are already new ones
DEBUG 2019-05-18 17:40:34,581 (SharedDocumentProvider.java:77) SharedDocumentProvider created by Eclipse
DEBUG 2019-05-18 17:40:40,095 (WhiteboardManager.java:194) WhiteboardManager instantiated
DEBUG 2019-05-18 17:40:40,236 (DocumentRecord.java:93) Added Node: attr(155819404023320506) name=svg
DEBUG 2019-05-18 17:40:40,493 (XMPPConnectionService.java:439) started Socks5 proxy on port: 7777 [listening on all interfaces]
DEBUG 2019-05-18 17:40:42,708 (XMPPConnectionService.java:459) using autodetected addresses: [192.168.77.1, 169.254.181.9, 192.168.38.1, 192.168.178.20, 2001:16b8:2876:8100:2130:fb9b:9c0f:28a, 2001:16b8:2876:8100:1889:76e2:5ede:bc98, fe80:0:0:0:2130:fb9b:9c0f:28a%wlan0, fe80:0:0:0:b91d:4084:d9a5:daa2%eth1, fe80:0:0:0:e5e3:781d:d5ae:b509%eth9, fe80:0:0:0:6d7b:3e0a:232a:c09a%eth11]
DEBUG 2019-05-18 17:40:42,713 (XMPPConnectionService.java:398)  new connection state == CONNECTING
DEBUG 2019-05-18 17:40:43,669 (XMPPConnectionService.java:398) maltesermailo@saros-con.imp.fu-berlin.de/Saros new connection state == CONNECTED
DEBUG 2019-05-18 17:40:43,670 (DataTransferManager.java:467) used transport order for the current XMPP connection: [XMPP-Socks5-Transport, XMPP-IBB-Transport]
DEBUG 2019-05-18 17:40:43,674 (SkypeManager.java:289) Refreshing Skype username cache...
ERROR 2019-05-18 17:40:44,323 (StunServiceImpl.java:263) error sending STUN request
java.net.SocketException: Network is unreachable: Datagram send failed
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketSend(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.send(DualStackPlainDatagramSocketImpl.java:136)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at de.fu_berlin.inf.dpp.net.stun.internal.StunServiceImpl$StunDiscovery$1.run(StunServiceImpl.java:255)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR 2019-05-18 17:40:44,323 (StunServiceImpl.java:263) error sending STUN request
java.net.SocketException: Network is unreachable: Datagram send failed
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketSend(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.send(DualStackPlainDatagramSocketImpl.java:136)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at de.fu_berlin.inf.dpp.net.stun.internal.StunServiceImpl$StunDiscovery$1.run(StunServiceImpl.java:255)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR 2019-05-18 17:40:44,323 (StunServiceImpl.java:263) error sending STUN request
java.net.SocketException: Network is unreachable: Datagram send failed
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketSend(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.send(DualStackPlainDatagramSocketImpl.java:136)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at de.fu_berlin.inf.dpp.net.stun.internal.StunServiceImpl$StunDiscovery$1.run(StunServiceImpl.java:255)
	at java.base/java.lang.Thread.run(Thread.java:834)
WARN  2019-05-18 17:40:54,322 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /192.168.38.1:0
WARN  2019-05-18 17:40:54,323 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /192.168.178.20:0
WARN  2019-05-18 17:40:54,322 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /192.168.77.1:0
WARN  2019-05-18 17:40:54,322 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /169.254.181.9:0
DEBUG 2019-05-18 18:27:56,817 (DiscoveryManager.java:382) Inserted DiscoveryInfo into Cache for: nightloewe@saros-con.imp.fu-berlin.de/Saros
DEBUG 2019-05-19 01:42:26,000 (DiscoveryManager.java:98) clearing cache entry of contact nightloewe@saros-con.imp.fu-berlin.de/Saros: <query xmlns="http://jabber.org/protocol/disco#info"><identity category="client" name="Smack" type="pc"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="urn:xmpp:ping"/><feature var="jabber:iq:last"/><feature var="http://jabber.org/protocol/commands"/><feature var="http://jabber.org/protocol/muc"/><feature var="http://jabber.org/protocol/bytestreams"/><feature var="http://jabber.org/protocol/xhtml-im"/><feature var="de.fu_berlin.inf.dpp"/><feature var="http://jabber.org/protocol/chatstates"/><feature var="http://jabber.org/protocol/disco#info"/></query>
ERROR 2019-05-19 01:42:26,004 (XMPPConnectionService.java:101) XMPP connection error: 
javax.net.ssl.SSLProtocolException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 14 more
ERROR 2019-05-19 01:42:26,064 (XMPPConnectionService.java:400)  new connection state == ERROR
javax.net.ssl.SSLProtocolException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 14 more
DEBUG 2019-05-19 01:42:26,070 (XMPPConnectionService.java:398)  new connection state == NOT_CONNECTED
DEBUG 2019-05-19 03:43:30,562 (UPnPServiceImpl.java:295) deleting existing port mappings
